:root{color-scheme:dark;--bg:#050505;--card:#111;--line:#2a2a2a;--gold:#f2c14e;--text:#fff;--muted:#b8b8b8}
*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:radial-gradient(circle at top,#1b1b1b,#050505 45%);color:var(--text);min-height:100vh}
a{color:inherit;text-decoration:none}.site-header{position:sticky;top:0;z-index:10;display:flex;justify-content:space-between;align-items:center;padding:16px 22px;background:rgba(0,0,0,.86);border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}
.brand{font-weight:900;color:var(--gold);letter-spacing:1px}.site-header nav{display:flex;gap:14px}.site-header nav a{color:#ddd;font-size:14px}
.page{max-width:1180px;margin:0 auto;padding:24px 16px 50px}.narrow{max-width:900px}.hero{padding:34px 20px;margin:14px 0 24px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(145deg,#171717,#0c0c0c);text-align:center}
.eyebrow{margin:0 0 8px;color:var(--gold);font-weight:800;font-size:12px;letter-spacing:1.6px}.hero h1,.article h1{margin:0 0 10px;font-size:clamp(28px,6vw,52px)}.hero p{color:var(--muted);margin:0}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;overflow:hidden;box-shadow:0 18px 45px rgba(0,0,0,.35)}.card img{width:100%;height:260px;object-fit:cover;display:block}.card-body{padding:16px}.card h2{margin:0 0 14px;font-size:20px}.btn,.card .btn{display:inline-flex;padding:11px 16px;border-radius:12px;background:linear-gradient(180deg,#ffe28a,#c99122);color:#111;font-weight:800}.empty{padding:30px;border:1px solid var(--line);border-radius:20px;background:var(--card);text-align:center;color:var(--muted)}
.article{background:var(--card);border:1px solid var(--line);border-radius:24px;padding:20px}.back{display:inline-block;margin-bottom:16px;color:var(--gold)}.article-img{width:100%;border-radius:18px;margin:12px 0 20px}.article-content{line-height:1.75;color:#eee}.article-content img{max-width:100%;border-radius:14px}
.login-wrap{min-height:100vh;display:grid;place-items:center;padding:20px}.login-card{width:min(420px,100%);background:#111;border:1px solid var(--line);border-radius:24px;padding:26px;box-shadow:0 20px 70px rgba(0,0,0,.45)}.login-card h1{margin-top:0}.login-card label,.form label{display:block;margin:12px 0 8px;color:#ddd;font-weight:700}.login-card input,.form input,.form textarea{width:100%;padding:13px 14px;border-radius:12px;border:1px solid #333;background:#050505;color:#fff;outline:none}.login-card button,.form button,.actions button{width:100%;margin-top:16px;padding:13px 16px;border:0;border-radius:12px;background:linear-gradient(180deg,#ffe28a,#c99122);color:#111;font-weight:900;cursor:pointer}.login-card small{display:block;margin-top:14px;color:#999}.alert{padding:12px;border-radius:12px;background:#3b1010;color:#ffb8b8;margin-bottom:12px}
.admin-shell{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.admin-side{background:#080808;border-right:1px solid var(--line);padding:22px;position:sticky;top:0;height:100vh}.admin-side h2{color:var(--gold)}.admin-side a{display:block;padding:12px 14px;margin:8px 0;border:1px solid #222;border-radius:12px;background:#111;color:#ddd}.admin-main{padding:24px;min-width:0}.admin-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.admin-head h1{margin:0}.admin-card{background:#111;border:1px solid var(--line);border-radius:20px;padding:18px;margin-bottom:18px}.form .check{display:flex;align-items:center;gap:10px}.form .check input{width:auto}.table{display:grid;gap:10px}.row{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:13px;border:1px solid #282828;border-radius:14px;background:#0a0a0a}.row small{display:block;color:#999;margin-top:4px}.actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.actions a,.actions button{display:inline-flex;width:auto;margin:0;padding:9px 12px;border-radius:10px;background:#222;color:#fff;font-size:13px}.actions form{margin:0}
@media(max-width:760px){.admin-shell{display:block}.admin-side{position:relative;height:auto}.row{display:block}.actions{margin-top:12px}.site-header{padding:14px}.card img{height:220px}}
